### ISSUE TITLE
[Compilation Error] error: use of undeclared identifier 'assert'

### ISSUE THREAD

**Issue by btparker** [luckybulldozer/VisualSFM_OS_X_Installer#15]
Hello, I am attempting to install VisualSFM on OSX (Yosemite), but I am encountering an error with assert. Disabling assert for boost yields more problems as well.

Relevant output for installation script:
```
Scanning dependencies of target cmvs_lib
[  1%] Building CXX object base/cmvs/CMakeFiles/cmvs_lib.dir/bundle.cc.o
In file included from /Users/...blah-blah.../VisualSFM_OS_X_Installer-master/CMVS-PMVS-master/program/base/cmvs/bundle.cc:10:
In file included from /Users/...blah-blah.../VisualSFM_OS_X_Installer-master/CMVS-PMVS-master/program/base/cmvs/bundle.h:12:
In file included from /usr/local/include/boost/graph/properties.hpp:19:
In file included from /usr/local/include/boost/property_map/property_map.hpp:600:
In file included from /usr/local/include/boost/property_map/vector_property_map.hpp:14:
In file included from /usr/local/include/boost/shared_ptr.hpp:17:
/usr/local/include/boost/smart_ptr/shared_ptr.hpp:916:9: error: use of undeclared identifier 'assert'
        BOOST_ASSERT( deleter_.use_count() <= 1 );
        ^
/usr/local/include/boost/assert.hpp:56:29: note: expanded from macro 'BOOST_ASSERT'
# define BOOST_ASSERT(expr) assert(expr)
                            ^
1 error generated.
make[2]: *** [base/cmvs/CMakeFiles/cmvs_lib.dir/bundle.cc.o] Error 1
make[1]: *** [base/cmvs/CMakeFiles/cmvs_lib.dir/all] Error 2
make: *** [all] Error 2
libpba.so failed to build, halting....
```

How should I go including assert, or is there a relevant build library I do not have installed correctly?

Thank you.

**Comment by btparker** [comment]
As assumed, this was an environment problem instead of a VisualSFM problem, but I was desperate. 

Turns out I had a conflicting assert.h included, the culprit being GStreamer.
```
sudo rm /Library/Frameworks/GStreamer.framework/Headers/assert.h
```
Hopefully this helps out other users Googling this same problem, closing the issue.

**Comment by Krzmbrzl** [comment]
> Hopefully this helps out other users Googling this same problem

It did - thank you very much for sharing this piece of information! I had a file called `Assert.h` in my include path and therefore I only had the error on case-insensitive file-systems.
This was really driving me nuts ^^
