### ISSUE TITLE
El Capitan Installation Error

### ISSUE THREAD

**Issue by mshodge** [luckybulldozer/VisualSFM_OS_X_Installer#23]
Hi there,

I've been trying to install VSFM on El Capitan but keep on getting an error code around:

cd build; ar -x ../lib/VisualSFM.a; cd ..;
Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-2.0' found

Then it's followed by a lot of error code. I've installed gtk+-2.x on my system, and have all the other packages installed I believe.

Anyone managed to install on El Capitan?

Thanks 
Michael

**Comment by uwe22** [comment]
I am following the instructions for mavericks. but I am having errors as well.
i can execute the script, but I seem to get stuck after unzipping the pba
Any help would be greatly appreciated.
Thanks 
UWE

I am attaching the end of the terminal output:

  inflating: pba/src/pba/ProgramCU.cu  
  inflating: pba/src/pba/ProgramCU.h  
  inflating: pba/src/pba/SparseBundleCPU.cpp  
  inflating: pba/src/pba/SparseBundleCPU.h  
  inflating: pba/src/pba/SparseBundleCU.cpp  
  inflating: pba/src/pba/SparseBundleCU.h  
  inflating: pba/src/pba/util.h      
Changing SiftGPU GCC to Brews gcc-4.9
Removing /usr/lib64 from makefile
Changing march from native core2 in makefile
Adding -L/usr/include/sys/ to compile Flags
patching file SparseBundleCPU.h
/Users/alaric/Documents/development/3d_reconstruction/VisualSFM_OS_X_Installer-master/pba
mkdir -p ./bin/out_no_gpu
mkdir -p ./bin 
g++-4.9 -w -o bin/out_no_gpu/pba.o src/pba/pba.cpp -DPBA_NO_GPU -fPIC -L -L/usr/lib -L/usr/include/sys/ -L./bin -O2 -Wall -Wno-deprecated -pthread -march=core2 -mfpmath=sse -fpermissive -c 
g++-4.9 -w -o bin/out_no_gpu/ConfigBA.o src/pba/ConfigBA.cpp -DPBA_NO_GPU -fPIC -L -L/usr/lib -L/usr/include/sys/ -L./bin -O2 -Wall -Wno-deprecated -pthread -march=core2 -mfpmath=sse -fpermissive -c 
g++-4.9 -w -o bin/out_no_gpu/SparseBundleCPU.o src/pba/SparseBundleCPU.cpp -DPBA_NO_GPU -fPIC -L -L/usr/lib -L/usr/include/sys/ -L./bin -O2 -Wall -Wno-deprecated -pthread -march=core2 -mfpmath=sse -fpermissive -c 
^[[A^[[B^[[B/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:19363:suffix or operands invalid for `movq'
/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:19385:suffix or operands invalid for `movq'
/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:42222:suffix or operands invalid for `movq'
/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:42233:suffix or operands invalid for `movq'
/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:42260:suffix or operands invalid for `movq'
/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:42275:suffix or operands invalid for `movq'
/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:42286:suffix or operands invalid for `movq'
/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:42456:suffix or operands invalid for `movq'
/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:42467:suffix or operands invalid for `movq'
/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:42494:suffix or operands invalid for `movq'
/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:42509:suffix or operands invalid for `movq'
/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:42520:suffix or operands invalid for `movq'
/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:44728:suffix or operands invalid for `movq'
/var/folders/45/gmhrzkj11hqcz41hvmr29p7h0000gp/T//ccBR5yUw.s:44745:suffix or operands invalid for `movq'
make: *** [bin/out_no_gpu/SparseBundleCPU.o] Error 1
libpba.so failed to build, halting.

**Comment by uwe22** [comment]
I tried a bit more I want to share with you what I did.

I manage to see the UI in El Capitan.
although I get the warning
(process:47244): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

I believe during the installation there is a conflict with mac ports on my system.
so before executing the install script I temporarily renamed my /opt/local folder to /opt/local2
I also changed the text encoding of terminal to windows ANSI, but I don't know if that has any influence.

During the installation I did a few times 

brew doctor

I also had an error with a cairo haeder not found. So I did

brew remove cairo

and then reinstalled

brew install --with-x11 cairo

here are the last lines of the output.
...
Scanning dependencies of target pmvs2
[ 99%] Building CXX object main/CMakeFiles/pmvs2.dir/pmvs2.cc.o
[100%] Linking CXX executable pmvs2
[100%] Built target pmvs2
CMVS & PMVS built... moving on
/Users/name/Documents/development/3d_reconstruction/VisualSFM_OS_X_Installer-master
Success!  Opening VSFM dir

**Comment by Ant01n3** [comment]
The 'brew install --with-x11 cairo' solved the problem for me. Thanks.

**Comment by FernandoTorres** [comment]
I had the same issue, but removing and re-installing with the `--with-x11` flag didn't work. 

Then I tried again adding the `--with-x11 --devel` and got it working.

**Comment by rasmi** [comment]
@uwe22 thanks for the tips -- moving /opt/local is what did the trick for me!
